# Generated by Django 4.0.6 on 2024-10-30 20:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('historique', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patrimoine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avenue', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('commune', models.CharField(choices=[('kikula', 'Kikula'), ('Likasi', 'Likasi'), ('Panda', 'Panda'), ('Shituru', 'Shituru')], max_length=10)),
                ('annee_construction', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1700)], verbose_name='annee de construction')),
                ('architecte', models.CharField(blank=True, max_length=100, null=True)),
                ('etat_conservation', models.CharField(choices=[('Bonne', 'Bonne'), ('Moyen', 'Moyen'), ('Mauvaise', 'Mauvaise'), ('En Rehabitation', 'En Rehabitation')], max_length=15)),
                ('affectation_actuel', models.CharField(max_length=200)),
                ('observation', models.CharField(default='aucunne obeservation', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='patrimoine/')),
            ],
        ),
        migrations.CreateModel(
            name='Fichier_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='plan/')),
                ('patrimoine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.patrimoine')),
            ],
        ),
    ]
